[package]
name = "forests"
description = "Forest types and operations in Rust."
version = "0.0.2"
authors = ["CrLF0710 <crlf0710@gmail.com>"]
license = "MIT"
repository = "https://github.com/crlf0710/forests-rs"
documentation = "https://docs.rs/forests"

[dependencies]
