(function() {var implementors = {};
implementors["forests"] = [{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"forests/struct.Forest.html\" title=\"struct forests::Forest\">Forest</a>&lt;T&gt;",synthetic:false,types:["forests::collections::Forest"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"forests/enum.SeekPos.html\" title=\"enum forests::SeekPos\">SeekPos</a>",synthetic:false,types:["forests::navigator::SeekPos"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"forests/enum.NavigateDir.html\" title=\"enum forests::NavigateDir\">NavigateDir</a>",synthetic:false,types:["forests::navigator::NavigateDir"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"forests/struct.node.html\" title=\"struct forests::node\">node</a>",synthetic:false,types:["forests::primitive::node"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"forests/enum.IterMode.html\" title=\"enum forests::IterMode\">IterMode</a>",synthetic:false,types:["forests::primitive::IterMode"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"forests/enum.IterMovement.html\" title=\"enum forests::IterMovement\">IterMovement</a>",synthetic:false,types:["forests::primitive::IterMovement"]},{text:"impl&lt;V:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a>, T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"forests/struct.Values.html\" title=\"struct forests::Values\">Values</a>&lt;V, T&gt;",synthetic:false,types:["forests::primitive::Values"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
